feat: добавлен API смены пароля
imozi/Guardian-of-the-Galaxy pull request #13
Opened 2022-12-03 09:05 UTC by putiniyama

### Добавление API смены пароля

2022-12-03 17:49 UTC, bin-umar commented on packages/client/src/api/password.ts
> +import axios from 'axios'
прогони линтер пжл, где-то одинарные ковички, где-то двойные. Е- единообразие :)

2022-12-03 17:50 UTC, bin-umar commented on packages/client/src/api/password.ts
> +export const passwordChange = (data: PasswordChange) => {
Получается она пока нигде не используется?

2022-12-03 17:52 UTC, putiniyama commented on packages/client/src/api/password.ts
> +export const passwordChange = (data: PasswordChange) => {
пока да, страницу смены делают)

2022-12-03 17:52 UTC, putiniyama commented on packages/client/src/api/password.ts
> +import axios from 'axios'
принял) исправляю)

2022-12-04 13:39 UTC, bin-umar requested changes
! https://github.com/imozi/Guardian-of-the-Galaxy/pull/14#pullrequestreview-1203507450

2022-12-04 13:47 UTC, putiniyama commented
я не понял откуда он нарисовался))

2022-12-04 15:33 UTC, bin-umar commented
> я не понял откуда он нарисовался))

1. Ты устанавливал зависимости через `npm install`, поэтому.
2. Посмотри какие файлы коммитишь перед `git commit`

2022-12-04 15:49 UTC, putiniyama commented
> 

понял, удалил)

2022-12-05 06:51 UTC, bin-umar approved these changes

2022-12-05 07:32 UTC, merged