feat: добавляет игру, обновляет компоненты, утилиты
imozi/Guardian-of-the-Galaxy pull request #30
Opened 2023-01-17 07:17 UTC by imozi

### Какую задачу решаем
Добавляет игру, корректирует и добавляет компоненты под игру, добавляет утилиты, добавляет новую страницу пользователя, навигацию пользователя.

2023-01-17 11:59 UTC, bin-umar commented
Очень большой PR, прощу в будущем прислать частями!

2023-01-17 12:05 UTC, bin-umar commented on packages/client/src/components/Ammunition/Ammunition.tsx
> +}
Not required, just a suggestion: 
```suggestion
export const Ammunition: FC<AmmunitionProps> = ({ ammun }) => {
  const list = [...Array(ammun).keys()];

  return (
      <ul className="ammunition">
        {list.map((el) => (
            <li key={el} className="ammunition__item" /> 
        ))}
      </ul>
  );
};

```

2023-01-17 12:13 UTC, bin-umar commented on packages/client/src/game/configs/EnemyShips.conf.ts
> +export const ENEMY_SHIPS = {
мб стоит тайпинг добавить чтобы на местах использование было автосадджесты?

2023-01-17 12:15 UTC, bin-umar commented on packages/client/src/game/configs/EnemyShips.conf.ts
> +export const ENEMY_SHIPS = {
Возможно придётся чуть помучаться тайскриптом, но если сделаешь будет полезно, подтянешь тс скилл

2023-01-17 12:17 UTC, bin-umar commented on packages/client/src/game/configs/EnemyShips.conf.ts
> +export const ENEMY_SHIPS = {
Или если посмотреть с другой стороны, почему так много ts конфигов? Мб стоит их хранить в .json? (Не пытаюсь утверждать что в json лучше)

2023-01-17 12:19 UTC, bin-umar commented on packages/client/src/game/model/EnemyController/EnemyController.ts
> +    [...Array(15).fill('scout')],
то что я говорил выше, кажется что у вас `dreadnought`, `torpedo`, и в конфиге должны называться одинакого чтобы не было ошибок. Поэтому их стоит вынести в enum

2023-01-17 12:20 UTC, bin-umar commented on packages/client/src/game/model/EnemyController/EnemyController.ts
> +        if (e) {
Слишком много уровеней вложенности, прощу упростить его https://learn.javascript.ru/coding-style#urovni-vlozhennosti

2023-01-17 12:20 UTC, bin-umar commented on packages/client/src/game/model/EnemyController/EnemyController.ts
> +        if (e) {
и что такое `e`? лучше назвать его `enemy`

2023-01-17 12:23 UTC, bin-umar commented on packages/client/src/game/model/EnemyController/EnemyController.ts
> +              ENEMY_CONTROLLER.positionAdjustment.indentColumnsEnemy
вижу что в 5и местах используется 
```ts
ENEMY_CONTROLLER.positionAdjustment.*
```
проще его один раз его вынести
```ts
const { positionAdjustment } = ENEMY_CONTROLLER
positionAdjustment.*
```

2023-01-17 12:26 UTC, bin-umar commented on packages/client/src/game/model/EnemyController/EnemyController.ts
> +      })
Сильно перегружанная функция, много разных вычислений, его стоит вынести как минимум в отдельную функцию, а в идеале в нескольких подфункций с понятными названиями чтобы понять что происходить.

Этот код сам не сможешь понять через неделю :)

2023-01-17 12:29 UTC, bin-umar commented on packages/client/src/game/model/Weapons/Weapons.ts
> +  }
Тоже перегружено, два вложенных Object.entries

2023-01-17 12:32 UTC, bin-umar commented on packages/client/src/game/model/СollisionController/СollisionController.ts
> +    ) {
Вот тут что происходит совсем непонятно, такие места лучше именовать каждое условие отдельно, типо:
```
      const ifAmmunIsSomething*** ammun.position.x + ammun.sizeSprite.w / 2 > mainShip.position.x - mainShip.sizeSprite.w / 2;
      // остальные условия
```

Такое условие будет трудным дебажить/читать/править. Вообще что либо делать с ним больно будет.

2023-01-17 12:33 UTC, bin-umar commented on packages/client/src/types/game/index.ts
> +export enum EnemyType {
есть ж enum, почему его не используешь?

2023-01-17 12:37 UTC, bin-umar requested changes
В целом код более менее написан аккуратно, но местами сильно перегруженная логика, и поверх этого почти неиспользуешь деструктуризацию, уровни вложенности 
Всё это сильно снижает уровень читаемости кода.

И тут проблема не только в том что мне тяжело ревьюит, а в том что остальным участникам команды тоже будет тяжело вдаваться в подробностях что происходит. + Как сказал выше ты сам будешь мучаться всё это дебажить/исправлять через пару недель. Старайся упростить код как можно больше.

2023-01-17 21:27 UTC, imozi commented
Прошу прощения, за большой пулреквест, игра делалась отдельно немного и нужно было ее перенести, попытался разбить по коммитам( эт последний раз такой большой ПР будет)

2023-01-17 21:55 UTC, imozi commented on packages/client/src/components/Ammunition/Ammunition.tsx
> +}
Спасибо, поправил, твое решение лучше и красивее будет)

2023-01-17 21:58 UTC, imozi commented on packages/client/src/types/game/index.ts
> +export enum EnemyType {
enum использую при генерации противников)

2023-01-18 06:33 UTC, imozi commented on packages/client/src/components/Ammunition/Ammunition.tsx
> +}
Сделано

2023-01-18 06:35 UTC, imozi commented on packages/client/src/game/configs/EnemyShips.conf.ts
> +export const ENEMY_SHIPS = {
Ну вроде получилось сделать)...да конфигов много но они разным объектам соответствуют удобней вносить изменения когда в разных файлах, а если все будет в одном пооока найдешь на какой строке)

2023-01-18 06:35 UTC, imozi commented on packages/client/src/game/model/EnemyController/EnemyController.ts
> +    [...Array(15).fill('scout')],
Сделал

2023-01-18 06:36 UTC, imozi commented on packages/client/src/game/model/EnemyController/EnemyController.ts
> +        if (e) {
Сделал

2023-01-18 06:36 UTC, imozi commented on packages/client/src/game/model/EnemyController/EnemyController.ts
> +              ENEMY_CONTROLLER.positionAdjustment.indentColumnsEnemy
Сделал

2023-01-18 06:37 UTC, imozi commented on packages/client/src/game/model/EnemyController/EnemyController.ts
> +      })
Постарался разбить ее, определение позиции в отдельные функции.

2023-01-18 06:38 UTC, imozi commented on packages/client/src/types/game/index.ts
> +export enum EnemyType {
Используется)

2023-01-18 22:27 UTC, imozi commented on packages/client/src/game/model/Weapons/Weapons.ts
> +  }
Сделано

2023-01-18 23:56 UTC, imozi commented on packages/client/src/game/model/СollisionController/СollisionController.ts
> +    ) {
Сделал, вынес в переменные условия

2023-01-19 07:59 UTC, bin-umar commented on packages/client/src/components/GameStartTimer/GameStartTimer.tsx
> +    <>
кажется это лишнее

2023-01-19 08:03 UTC, bin-umar commented on packages/client/src/game/model/CollisionController/CollisionController.ts
> +    }
```suggestion
    return isCollidRight && isCollidLeft && isCollidTop && isCollidBottom
```

2023-01-19 08:04 UTC, bin-umar commented on packages/client/src/game/model/CollisionController/CollisionController.ts
> +    }
```suggestion
    return isCollidRight && isCollidLeft && isCollidTop && isCollidBottom
```

2023-01-19 08:04 UTC, bin-umar commented on packages/client/src/game/model/CollisionController/CollisionController.ts
> +    }
```suggestion
    return isCollidRight && isCollidLeft && isCollidTop && isCollidBottom
```

2023-01-19 08:07 UTC, bin-umar commented on packages/client/src/game/model/EnemyController/EnemyController.ts
> +    [...Array(15).fill('scout')],
```suggestion
    [EnemyType. battlecruiser, EnemyType.dreadnought, EnemyType.battlecruiser],
    [...Array(5).fill(EnemyType.torpedo)],
    [...Array(9).fill(EnemyType.frigate)],
    [...Array(13).fill(EnemyType.bomber)],
    [...Array(13).fill(EnemyType.support)],
    [...Array(13).fill(EnemyType.fighter)],
    [...Array(15).fill('scout')],
```

2023-01-19 08:11 UTC, bin-umar commented on packages/client/src/game/model/EnemyShip/EnemyShip.ts
> +    )
```suggestion
    const { position: { x, y }, _typeWeapon, _damageLimit } = this

    this._ammunition.push(
      this._weapons[_typeWeapon](
        { x, y },
        'topY',
        _damageLimit
      )
    )
```
P.S. `_weapons` и `_ammunition` не стоит деструктуризировать потому что приводят к ошибкам

2023-01-19 08:13 UTC, bin-umar approved these changes

2023-01-19 10:13 UTC, imozi commented on packages/client/src/components/GameStartTimer/GameStartTimer.tsx
> +    <>
Поправил)

2023-01-19 10:13 UTC, imozi commented on packages/client/src/game/model/CollisionController/CollisionController.ts
> +    }
А ну да можно же было так сделать))) Спасибо))

2023-01-19 10:14 UTC, imozi commented on packages/client/src/game/model/EnemyShip/EnemyShip.ts
> +    )
Поправил, забываю про деструктуризацию) привыкнуть не могу ни как)

2023-01-19 10:15 UTC, imozi commented
Спасибо большое за ревью и полезные замечания, еще раз прошу прощения за такой большой ПР 🙏🏻

2023-01-19 10:19 UTC, merged