feat: Реализация темизации
imozi/Guardian-of-the-Galaxy pull request #42
Opened 2023-02-06 15:23 UTC by AnyaChernova

https://user-images.githubusercontent.com/40361915/217011699-9edef6eb-42bd-4b95-9366-11ff642076ad.mp4

2023-02-06 17:11 UTC, bin-umar commented on packages/client/src/components/AudioPlayer/AudioPlayer.tsx
> +  const audio = isBrowser() ? new Audio('sounds/a31df44c3944ea6.mp3') : null
я как-то раз просил кажется что пожалуйста не хардкодьте значение. Audioplayer должен принять его в качестве пропса, можете потом его указать как дефолтное значение, но никак hardcode

2023-02-06 17:12 UTC, bin-umar commented on packages/client/src/components/Card/Card.scss
> +  border: 2px solid var(--color-primary);
Круто что решили перейти на css переменные. Можно узнать какая была необходимость/причина?

2023-02-06 17:14 UTC, bin-umar commented on packages/server/src/controllers/userController.ts
> +      // @ts-expect-error
обычно после него пишется причина по которой она expected

2023-02-06 17:16 UTC, bin-umar requested changes
1. Почему недостаточно было хранить тему локально?
2. Где можно кликать игру?)))

2023-02-06 17:18 UTC, AnyaChernova commented on packages/client/src/components/Card/Card.scss
> +  border: 2px solid var(--color-primary);
так удобнее при смене темы обновлять все цвета

2023-02-06 17:22 UTC, AnyaChernova commented
> 1. Почему недостаточно было хранить тему локально?
> 2. Где можно кликать игру?)))

1. вроде в условии задания было хранить в базе
2. пока нигде( на след неделе только планируем деплоить

2023-02-06 17:32 UTC, AnyaChernova commented on packages/server/src/controllers/userController.ts
> +      // @ts-expect-error
done

2023-02-06 17:32 UTC, AnyaChernova commented on packages/client/src/components/AudioPlayer/AudioPlayer.tsx
> +  const audio = isBrowser() ? new Audio('sounds/a31df44c3944ea6.mp3') : null
done

2023-02-06 20:12 UTC, bin-umar commented on packages/client/src/components/Card/Card.scss
> +  border: 2px solid var(--color-primary);
Да, ок)

2023-02-06 20:13 UTC, bin-umar commented on packages/server/src/controllers/userController.ts
> +      // @ts-expect-error Property 'themeName' does not exist on type 'Model'
Почему бы его не добавить?

2023-02-06 20:13 UTC, bin-umar approved these changes

2023-02-06 20:14 UTC, bin-umar commented
> 2. пока нигде( на след неделе только планируем деплоить

Эх, жаль.

2023-02-07 04:34 UTC, AnyaChernova commented on packages/server/src/controllers/userController.ts
> +      // @ts-expect-error Property 'themeName' does not exist on type 'Model'
оно там есть, но ts почему-то его тут не видит, не разобралась почему

2023-02-07 05:01 UTC, merged